Repository apache/skywalking-php, pull requests merged in 2022-10, with the labels that each got.

#12 Update PECL user
  package.tpl.xml
Labels: enhancement

#14 Update compiling project document.
  docs/en/contribution/compiling.md
Labels: documentation

#17 Update readme about creating issue.
  README.md
Labels: documentation

#19 Add swoole support.
  .github/workflows/rust.yml
  README.md
  docs/en/setup/service-agent/php-agent/Supported-list.md
  src/lib.rs
  src/module.rs
  src/plugin/mod.rs
  src/request.rs
  tests/common/mod.rs
  tests/conf/php.ini
  tests/data/expected_context.yaml
  tests/e2e.rs
  tests/php/swoole/main.1.php
  tests/php/swoole/main.2.php
Labels: enhancement

#22 Take care of PDO false and DSN tailing semicolons.
  config.m4
  src/plugin/plugin_pdo.rs
  tests/data/expected_context.yaml
  tests/php/fpm/pdo.php
Labels: enhancement

#24 Save PDO exceptions.
  config.m4
  src/channel.rs
  src/exception_frame.rs
  src/lib.rs
  src/plugin/plugin_pdo.rs
  tests/data/expected_context.yaml
  tests/php/fpm/pdo.php
Labels: bug

#25 Update minimal supported PHP version to 7.2.
  .github/workflows/rust.yml
  README.md
  docs/en/setup/service-agent/php-agent/README.md
Labels: documentation

#26 Utilize UnixListener for the worker process to accept reports.
  Cargo.lock
  Cargo.toml
  src/channel.rs
  src/module.rs
  src/worker.rs
Labels: enhancement

#28 Kill the worker on module shutdown.
  src/module.rs
  src/worker.rs
Labels: enhancement
