Repository apache/skywalking-php, pull requests merged in 2022-11, with the labels that each got.

#30 Upgrade rust mini version to 1.65.
  Cargo.lock
  Cargo.toml
  src/execute.rs
  src/module.rs
  src/request.rs
Labels: enhancement

#31 Add missing request_id.
  src/plugin/plugin_mysqli.rs
  src/plugin/plugin_pdo.rs
  src/plugin/plugin_predis.rs
Labels: bug

#32 Adapt virtual cache.
  src/plugin/plugin_memcached.rs
  src/plugin/plugin_pdo.rs
  src/plugin/plugin_predis.rs
  src/plugin/plugin_redis.rs
  src/tag.rs
  tests/data/expected_context.yaml
  tests/php/fpm/memcached.php
Labels: enhancement

#33 Fix permission denied of unix socket.
  Cargo.lock
  Cargo.toml
  src/module.rs
  src/util.rs
  src/worker.rs
Labels: bug

#35 Make explicit rust version requirement
  docs/en/contribution/compiling.md
Labels: documentation
